import {useEffect, useState} from 'react'
import '../../styles.scss'
import Spotify from '../../api/Spotify';
import getHost from '../../api/getHost';

function HostDashboard() {
    const [playlist, setPlaylist] = useState()
    useEffect(() => {
        const getPlaylist = async () => {
            const host_id = localStorage.getItem('host_id', '');
            const response = await getHost.getHostById(host_id);
            return response;
        }
        const getTracks = async () => {
            const host = await getPlaylist();
            const response = await Spotify.getTracks(host.playlist, "/host/dashboard");
            setPlaylist(response);
        }
        getTracks();
    }, []);
    return (
        <>
        <div className="dashboard-bg">
            <div className="dashboard-component">
                <h2>See what your users have been upto.</h2>
                <p>In this dashboard, you can view the dynamic playlist generated by your users.</p>
            </div>
            <div className="line"></div>
            <div className="dashboard-component">
                <div className="playlist-box">
                    <div className="headings">
                    <h3 style={{textAlign: 'center'}}>Votes</h3>    
                    <h3 style={{textAlign: 'center'}}>Track</h3>
                    </div>
                    <div className="tracks-grid">
                        {playlist && playlist.map((track) => {
                            return (
                                <div className='track-container'>
                                <div className="vote-details">
                                    <p style={{textAlign:'center'}}>{track.votes}</p>
                                </div>
                                    <div className="track-details">
                                        <img src={track.album.images ? track.album.images[0].url : ''} alt="track-art"/>
                                        <p>{track.name}</p>
                                        <p></p>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        </div>
        <div className="ocean">
        <div className="wave"></div>
        <div className="wave"></div>
        </div>
        </>
  )
}

export default HostDashboard